name: Deploy pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Build & deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_SSH_KEY}}
          script: |
            cd ~/endgame-phase-2 || git clone https://github.com/adil-rahman-mt/endgame-phase-2.git
            cd ~/endgame-phase-2
            git pull origin main

            sudo docker build -t fe-img:latest .
            sudo docker stop fe-cont || true
            sudo docker rm fe-cont || true

            sudo docker run -d --restart unless-stopped \
            -p 5005:5005 \
            -e DB_URL="${{ secrets.DB_URL }}" \
            -e FLASK_JWT_SECRET_KEY="${{ secrets.FLASK_JWT_SECRET_KEY }}" \
            -e FLASK_SECRET_KEY="${{ secrets.FLASK_SECRET_KEY }}" \
            -e EC2_HOST="${{ secrets.EC2_HOST }}" \
            --name fe-cont \
            fe-img:latest
            